export enum EndPoints {
  LandingPageData = 'LandingPage/get-landing-page-data',
  UserTableData = 'Users/get-users-by-pagination',
  Login = 'authentication/login',
  RefreshToken = 'authentication/refersh-token',
  VerifyResetPasswordToken = 'authentication/verify-token-reset-password',
  UserExport = 'Users/user-export-data',
  ForgotPassword = 'Authentication/forgot-password',
  ResetPassword = 'Authentication/reset-password',
  RegisterUser = 'Authentication/register-user',
  VerifyTokenRestPassword = 'Authentication/verify-token-reset-password',
  GetUserById = 'Users/get-user-by-id',
  CreateOrUpdateUser = 'Users/create-or-update-user',
  QuizDifficultyLevel = 'QuizDifficultyLevel/get-quiz-difficulty-list',
  QuizDifficultyNameAvailable = 'QuizDifficultyLevel/is-difficulty-name-available',
  CreateQuizDifficultyLevel = 'QuizDifficultyLevel/create-difficulty-level',
}
