export enum Navigations {
  Login = 'login',
  ForgetPassword = 'forgot-password',
  ResetPassword = 'reset-password',
  ResetPasswordLink = 'reset-password-link',
  ResetPasswordLinkSuccess = 'reset-password-link-success',
  ResetLinkInvalid = 'reset-link-invalid',

  User = 'user',
  Dashboard = 'dashboard',
  QuizList = 'quizzes',
  BrowseQuizzes = 'browse-quizzes',
  QuizAttempt = 'quiz-attempt',
  QuizInstruction = 'quiz-instruction',
  QuizResult = 'quiz-result',
  Battles = 'battles',
  BattleList = 'battle-list',
  BattleInstruction = 'battle-instruction',
  BattleAttempt = 'battle-attempt',
  BattleResult = 'battle-result',
  SearchOpponent = 'search-opponent',
  Tournaments = 'tournaments',
  Leaderboards = 'leaderboards',
  Profile = 'profile',

  Admin = 'admin',
  Users = 'user-management',
  Quizzes = 'quiz-management',
  Categories = 'quiz-categories',
  Difficulties = 'difficulty-levels',
  BattlesAdmin = 'battle-management',
  QuestionPool = 'questions-pool',
  QuestionDifficulty = 'question-difficulty',
  EmailTemplates = 'email-templates',
  Settings = 'platform-settings',
  AiConfig = 'ai',
  Finance = 'financial-management',
  Notifications = 'notification-center',

  Unauthorized = 'unauthorized',

  QuizCreation = 'quiz-creation',

  BattleCreation = 'battle-creation',
  BattleUpdation = 'edit-battle',
}
